Code-the-Dream-School/gg-pac-team3-monorepo

backend/README.md
backend/package-lock.json
backend/package.json
backend/src/app.mjs
backend/src/middlewares/verifyToken.mjs
backend/src/routes/courseRoutes.mjs
backend/src/routes/lessonRoutes.mjs
backend/src/routes/quizRoutes.mjs
backend/src/routes/userCourseRoutes.mjs
backend/src/routes/userRoutes.mjs

Updated routes files to include swagger documentation.
Updated the Readme file to explain how to use Swagger UI for API documentation.
**How to Test:**
1. Launch the server by running the project.
2. Go to http://localhost:8000/api-docs in your web browser.
3. Click on the "Authorize" button at the top of the Swagger UI and enter a valid token."

Swagger documentation

---

server/controllers/courseController.mjs

Added filter in API to filter any course data that causes error in displaying on the front page.

filter courses with invalid data

---

server/app.mjs
server/routes/courseRoutes.mjs
server/routes/lessonRoutes.mjs

- Update the path of the routes folder from the old folder structure to the new folder structure in app.mjs
- Update the response schema of courseController and lessonController creation. CourseId and lessonId are managed by the Firestore database, not the frontend.

fix path and response schemas

---

server/controllers/userCourseController.mjs

added filter function to filter invalid course in userCourseController

added filtering for invalid courses

---

server/routes/courseRoutes.mjs
src/pages/NewCourse/NewCourse.jsx
src/pages/TeacherDashboard/TeacherDashboard.jsx

- minor fix for teacher dashboard change 'token' to 'authToken' 
- added isTeacher in '/teacher_courses'

fix bug in teacher dashboard

---

src/AuthContext.jsx

Made small changes in AuthContext file.

made changes in AuthContext file

---

server/controllers/courseController.mjs

Bug fixed in coursecontroller.mjs file

Bug fixed in coursecontroller.mjs file

---

server/controllers/userController.mjs

Fix a minor bug in the default profile picture, since we already have an image available in /public/images saved in our main just use that instead.

replaced the default profile pic

---

server/controllers/courseController.mjs
server/controllers/userFeedbackController.mjs
server/routes/courseRoutes.mjs
server/routes/userFeedbackRoutes.mjs
src/components/layout/Nav.jsx
src/pages/CourseDetails/CourseDetails.jsx
src/pages/CourseDetails/CourseDetails.module.css
src/pages/Learn/CourseInfo.jsx
src/pages/Learn/CourseInfo.module.css
src/pages/Learn/Learn.jsx
src/pages/Learn/Learn.module.css
src/pages/Learn/Lesson.jsx
src/pages/Learn/Lesson.module.css
src/pages/Learn/Quiz.module.css
src/pages/Learn/UserFeedback.jsx
src/pages/Learn/UserFeedback.module.css
src/pages/UserDashboard/Courses.module.css
src/pages/UserDashboard/Home.jsx
src/pages/UserDashboard/UserDashboard.module.css
src/services/api.js

I made small changes to a few files and added a rating feature for the courses.
Added a course type option for users to search for courses based on their course type preferences. Added pagination option too.
Ratings for all courses are displayed based on user feedback. Only courses with lessons have ratings available.
Added a back button to the form for users to return to the previous page, and updated the style and font. 
same here - Added a back button to the form for users to return to the previous page, and updated the style and font.

Styles change and bug fix branch 2

---

__tests__/backend/lessonController.tests.mjs
__tests__/backend/userController.tests.mjs
__tests__/backend/userCourseController.tests.mjs
__tests__/backend/userFeedbackRoutes.tests.mjs
package-lock.json
package.json
server/controllers/lessonController.mjs
server/controllers/userCourseController.mjs
src/components/layout/Nav.jsx

Finished the backend testing for new updated controllers.

Testing part 4

---

src/pages/Learn/CourseInfo.module.css
src/pages/Learn/Learn.jsx
src/pages/UserDashboard/Courses.module.css
src/pages/UserDashboard/Home.jsx
src/pages/UserDashboard/MyCourses.jsx

made small changes in Home.jsx file

made small changes in Home.jsx file

---

__tests__/frontend/SignIn.tests.mjs
__tests__/frontend/frontpage.tests.mjs

Minor bug fix, The element name has changed because of the new CSS design merge.
added timeout for frontpage test

frontend test bug

---

package.json
server/config/firebase.mjs

Added the node version and a start script for our server.
Edit firebase.config to store firebase SDK in the render secret files folder.

set-up package.json for deployment

---

package-lock.json
package.json

npm install for package-lock.json

run npm install for deployment

---

package-lock.json
package.json

Deployment keeps failing. Have to do rm -rf node_modules package-lock.json and npm install

module clean up and reinstall

---

src/App.jsx

corrected wrong path in App.jsx

corrected wrong path in App.jsx

---

package.json

added client to run both

---

package.json

added script

---

package.json

edit script

---

src/pages/CourseDetails/CourseDetails.jsx
src/pages/CourseDetails/CourseDetails.module.css
src/pages/Learn/Learn.jsx
src/pages/Learn/Learn.module.css
src/pages/Learn/Lesson.module.css
src/pages/Learn/Quiz.jsx
src/pages/Learn/Quiz.module.css
src/pages/UserDashboard/Courses.module.css
src/pages/UserDashboard/Home.jsx
src/pages/UserDashboard/MyCourses.jsx

Minor changes

---

server/app.mjs
server/routes/userFeedbackRoutes.mjs

routes corrected base on render log

routes corrected base on render log

---

server/app.mjs

render console.log to find routes conflict

render console.log to find routes conflict

---

server/app.mjs
server/server.mjs

move the console log in the server

move the console log in the server

---

server/app.mjs
server/server.mjs

remove log and static as they are not working anyway

remove log and static as they are not working anyway

---

server/app.mjs
vite.config.js

trying a different approach in deploying,  adding a public folder in the server where render can store client side after build.

Deployment1

---

server/app.mjs

remove main route

---

server/app.mjs

re deployment

---

server/app.mjs

putting back main
